from aiogram.fsm.state import State, StatesGroup


class CryptoBotStates(StatesGroup):
    start = State()
    loyalty_intro = State()
    loyalty_details = State()
    nationality = State()
    residence = State()
    fiat_currency = State()
    amount = State()
    crypto = State()
    payment_method = State()
    wallet_or_broker = State()
    broker_code = State()
    user_wallet_direct = State()
    user_wallet = State()
    gen_address = State()
    payment_instructions = State()
    kyc_check = State()
    manual_high_fee = State()
    confirmation = State()
    loyalty_status = State()
    history = State()
    operator = State()
